export const types = {
  LOAD_CHARACTERS: 'UI_LOAD_CHARACTERS',
  SET_CHARACTERS: 'UI_SET_CHARACTERS',
  SET_CHARACTERS_ERROR: 'UI_SET_CHARACTERS_ERROR',
  SET_CHARACTERS_LOADING: 'UI_SET_CHARACTERS_LOADING',
  LOAD_PLANETS: 'UI_LOAD_PLANETS',
  SET_PLANETS: 'UI_SET_PLANETS',
  SET_PLANETS_ERROR: 'UI_SET_PLANETS_ERROR',
  SET_CHARACTERS_COUNT: 'UI_SET_CHARACTERS_COUNT',
  SET_CURRENT_PAGE: 'UI_SET_CURRENT_PAGE',
}
